services:
  - type: web
    name: pie-party
    env: node
    repo: https://github.com/animeshf/PieParty
    branch: main
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node server.js"
